# Generated by Django 5.2 on 2025-11-17 16:34

from django.db import migrations, models


def assign_public_ids(apps, schema_editor):
    Upload = apps.get_model("hub", "Upload")
    for upload in Upload.objects.filter(public_id__isnull=True):
        upload.public_id = f"ID{upload.pk}"
        upload.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.RunPython(assign_public_ids, migrations.RunPython.noop),
    ]
